spring:
  application:
    name: microservice-ai
  datasource:
    url: jdbc:mysql://localhost:3306/ai_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      discovery:
        enabled: true
        service-id: microservice-config

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.ai.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
